### PR TITLE
Fix EP error

### PR DESCRIPTION
**Pull request by Diet-Cola**

### CODE REVIEW

**Comment by Protonull** [comment]
Okay, we deduced that the error originated from Tuinity / Paper / Spigot since neither BanStick nor ExilePearl had been changed in any way for more than 10 days. We didn't exactly know how or why, so we created a command in ExilePearl to tell us whether it could access BanStick's database, and it couldn't. We added a scheduled repeating task to CivModCore that reflected its way to BanStick's database instance and lo and behold, it existed. So simultaneously it *is* accessible to CivModCore, which doesn't depend on BanStick, but *isn't* accessible to ExilePearl which does depend on BanStick.. weird. After looking at the POM we saw that BanStick was being shaded.

CivModCore was able to access BanStick's database because it was seeing *BanStick's* version of the code.. whereas ExilePearl and EssenceGlue (which depends on ExilePearl) was only seeing the shaded version of BanStick, which wasn't being used for anything thus lacked any database connections.

We believe that some change within Tuinity / Paper / Spigot has done something to further separate plugins from each other, hence why this problem only started within the [last 48 hours after an upstream merge](https://github.com/Tuinity/Tuinity/commit/f0e91a4ae9c511c116c859105d10b02dddbe4f71).

**Comment by wingzero54** [comment]
The joys of being tied to Tuinity which automatically updates itself amirite

**Comment by Protonull** [comment]
It's not Tuinity's fault here, we would've had the same problem on Paper. Seems like the issue came from Spigot: https://github.com/PaperMC/Paper/commit/cb896d4710c2a827281f701682bbb8e0afff0818

**Comment by wingzero54** [comment]
So our parent's parent's parent caused the issue

**Comment by Protonull** [comment]
Yup :P now just imagine if we were on Airplane, then it'd be our parent's parent's parent's parent's parent.

**Pull request merged**
