### PR TITLE
Prevent elytra usage with pearl in inventory

### PR DESCRIPTION
**Pull request by Diet-Cola**
Also prevents pearl pickup when flying

### CODE REVIEW

**Comment by Diet-Cola** [comment]
On test

**Comment by okx-code** [comment]
Probably quite a good idea actually

**Comment by Protonull** [comment]
Sounds like an excellent idea

**Comment by Protonull** [comment]
It would be way funnier though if you dropped your pearls when trying to fly, rather than just refusing the flight.. imagine someone trying to jetpack out of a fight, yeeting themselves away only to leave a pile of pearls behind

**Pull request merged**
